[package]
name = "lievre-federation"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lievre-core = { path = "../core" }
lievre-shared = { path = "../shared" }

serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
thiserror.workspace = true
url = { version = "2", features = ["serde"] }
anyhow = "1"
activitypub_federation = { version = "0.6", default-features = false, features = ["axum"] }
activitystreams-kinds = "0.3"
reqwest = { version = "0.12", features = ["json"] }
tokio = { workspace = true }
axum = { workspace = true }
sqlx.workspace = true
tracing.workspace = true
